"""remover unique constraint do email do cliente

Revision ID: 2802eddfab93
Revises: 3e2f3d68dddc
Create Date: 2026-09-08 10:43:42.326010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2802eddfab93'
down_revision: Union[str, Sequence[str], None] = '3e2f3d68dddc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('clients_email_key'), 'clients', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('clients_email_key'), 'clients', ['email'])
    # ### end Alembic commands ###
