"""baseline: esquema inicial

Revision ID: 3e2f3d68dddc
Revises:
Create Date: 2026-08-01 21:16:28.388712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e2f3d68dddc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_number', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('locality', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('nif', sa.String(length=20), nullable=True),
    sa.Column('origin', sa.String(length=60), nullable=True),
    sa.Column('proposal_status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('proposal_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_clients_client_number'), 'clients', ['client_number'], unique=True)
    op.create_table('client_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('installations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('power_kwp', sa.Float(), nullable=True),
    sa.Column('num_modules', sa.Integer(), nullable=True),
    sa.Column('module_model', sa.String(length=120), nullable=True),
    sa.Column('inverter_model', sa.String(length=120), nullable=True),
    sa.Column('inverter_power_kw', sa.Float(), nullable=True),
    sa.Column('battery_model', sa.String(length=120), nullable=True),
    sa.Column('battery_capacity_kwh', sa.Float(), nullable=True),
    sa.Column('installation_date', sa.Date(), nullable=True),
    sa.Column('roof_type', sa.String(length=60), nullable=True),
    sa.Column('orientation', sa.String(length=30), nullable=True),
    sa.Column('tilt_degrees', sa.Float(), nullable=True),
    sa.Column('estimated_annual_kwh', sa.Float(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_table('interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('interaction_type', sa.String(length=40), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('outcome', sa.String(length=120), nullable=True),
    sa.Column('next_action', sa.String(length=255), nullable=True),
    sa.Column('next_action_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_ordem', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('entidade_emissora', sa.String(length=120), nullable=True),
    sa.Column('num_factura', sa.String(length=60), nullable=True),
    sa.Column('valor_siva', sa.Float(), nullable=True),
    sa.Column('iva', sa.Float(), nullable=True),
    sa.Column('iva_pct', sa.Float(), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('tipo_movimento', sa.String(length=30), nullable=True),
    sa.Column('categoria', sa.String(length=20), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transacoes_cliente_id'), 'transacoes', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_transacoes_data'), 'transacoes', ['data'], unique=False)
    op.create_index(op.f('ix_transacoes_numero_ordem'), 'transacoes', ['numero_ordem'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transacoes_numero_ordem'), table_name='transacoes')
    op.drop_index(op.f('ix_transacoes_data'), table_name='transacoes')
    op.drop_index(op.f('ix_transacoes_cliente_id'), table_name='transacoes')
    op.drop_table('transacoes')
    op.drop_table('interactions')
    op.drop_table('installations')
    op.drop_table('client_documents')
    op.drop_index(op.f('ix_clients_client_number'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
